apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: jaganikuman/benricontainer
    command:
    - sleep
    - infinity
    resources:
      requests:
        cpu: 200m
        memory: 128M
