version: 2.1
executors:
  default:
    docker:
      - image: google/cloud-sdk:241.0.0
jobs:
  build:
    executor:
      name: default
    steps:
    - checkout
    - run:
        name: docker push
        command: |
          pwd
          ls -al
          cat .git/config
          git branch

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build